#!perl

# DATE
# VERSION

use strict;
use warnings;
use App::DAVThis;

App::DAVThis->new->run;

# ABSTRACT: Export the current directory over WebDAV
# PODNAME:

=head1 SYNOPSIS

 ## Export the current directory over WebDAV
 $ dav_this

You can then use a WebDAV client like the command-line C<cadaver> or the GUI
C<nautilus> (dav://localhost:4242/)

 ## Export the `dir_name` directory over WebDAV, specify port
 $ dav_this dir_name --port 8242

 ## Show documentation about our options
 $ dav_this --help

 ## Show the entire man page
 $ dav_this --man


=head1 DESCRIPTION

This script exports the current directory over WebDAV.


=head1 ARGUMENTS

The script accepts a single optional argument: the path of the directory to
export.

=head1 OPTIONS

The following options are available:

=over 4

=item --port PORT

Start the FTP server on a specific C<PORT>. Default is 4242.

=item --help

Print information about the script usage and its options.

=item --man

Print the entire man page for the command.

=back


=head1 TODO


=head1 SEE ALSO

Other scripts in the same spirit: L<http_this> (from L<App::HTTPThis>),
L<https_this> (from L<App::HTTPThis>), L<ftp_this> (from L<App::FTPThis>),
L<cgi_this> (from L<App::CGIThis>).
